name: Build Flutter iOS App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Get source
        run: |
          wget https://www.season-studio.top/flutter_test.tar.gz
          tar -zxvf flutter_test.tar.gz
          ls

      - name: Build iOS .ipa
        run: |
          cd flutter_test.tar.gz
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
